CREATE TABLE [dbo].[USUARIO] (
    [IDUSUARIO]    UNIQUEIDENTIFIER NOT NULL,
    [NOME]         NVARCHAR (150)   NOT NULL,
    [EMAIL]        NVARCHAR (100)   NOT NULL,
    [SENHA]        NVARCHAR (50)    NOT NULL,
    [DATACADASTRO] DATETIME         NOT NULL,
    PRIMARY KEY CLUSTERED ([IDUSUARIO] ASC),
    UNIQUE NONCLUSTERED ([EMAIL] ASC)
);



CREATE TABLE FUNCIONARIO (
 IDFUNCIONARIO UNIQUEIDENTIFIER NOT NULL,
 NOME NVARCHAR(150) NOT NULL,
 EMAIL NVARCHAR(100) NOT NULL,
 TELEFONE NVARCHAR(20) NOT NULL,
 FOTO NVARCHAR(150) NOT NULL,
 DATANASCIMENTO DATE NOT NULL,
 DATAADMISSAO DATE NOT NULL,
 SALARIO DECIMAL(7,2) NOT NULL,
 CPF NVARCHAR(11)NOT NULL,
 CARGO NVARCHAR(150) NOT NULL,
 IDUSUARIO UNIQUEIDENTIFIER NOT NULL,
 PRIMARY KEY(IDFUNCIONARIO),
 FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(IDUSUARIO))
GO
